### ISSUE TITLE
Unable to compile example #2

### ISSUE THREAD

**Issue by MadMax411** [madf/jwtxx#14]
The build of the library works well, but I'm not able to compile the second examples.

Source code: 
https://github.com/madf/jwtxx#rs256

Compile command: 
$ g++ -Wall -ljwtxx -std=c++11 test_jwt.cpp

Output:
/tmp/ccwPesGx.o: In function `main':
test_jwt.cpp:(.text+0x113): undefined reference to `JWTXX::JWT::JWT(JWTXX::Algorithm, std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > >, std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > >)'
test_jwt.cpp:(.text+0x1cb): undefined reference to `JWTXX::JWT::token(std::string const&, std::function<std::string ()> const&) const'
test_jwt.cpp:(.text+0x223): undefined reference to `JWTXX::Validate::exp(long)'
test_jwt.cpp:(.text+0x2b0): undefined reference to `JWTXX::Key::Key(JWTXX::Algorithm, std::string const&, std::function<std::string ()> const&)'
test_jwt.cpp:(.text+0x2d4): undefined reference to `JWTXX::JWT::JWT(std::string const&, JWTXX::Key, std::vector<std::function<JWTXX::ValidationResult (std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&)>, std::allocator<std::function<JWTXX::ValidationResult (std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&)> > >&&)'
test_jwt.cpp:(.text+0x2e3): undefined reference to `JWTXX::Key::~Key()'
test_jwt.cpp:(.text+0x39a): undefined reference to `JWTXX::JWT::claim(std::string const&) const'
test_jwt.cpp:(.text+0x3e4): undefined reference to `JWTXX::JWT::claim(std::string const&) const'
test_jwt.cpp:(.text+0x406): undefined reference to `JWTXX::algToString(JWTXX::Algorithm)'
test_jwt.cpp:(.text+0x611): undefined reference to `JWTXX::Key::~Key()'
collect2: error: ld returned 1 exit status

Where's the error? Or what I'm doing wrong?

**Comment by madf** [comment]
Try putting -ljwtxx after test_jwt.cpp

**Comment by MadMax411** [comment]
After changing the position of the library I get some other errors. Adding "-lssl -lcrypto" doesn't change anything. Are the includes for OpenSSL are missing?

$ g++ -std=c++11 test_jwt.cpp -ljwtxx

//usr/local/lib/libjwtxx.a(jwt.cpp.o): In function `JWTXX::Base64URL::encode(JWTXX::Base64URL::Block const&)':
jwt.cpp:(.text+0x2f9): undefined reference to `BIO_s_mem'
jwt.cpp:(.text+0x301): undefined reference to `BIO_new'
jwt.cpp:(.text+0x309): undefined reference to `BIO_f_base64'
jwt.cpp:(.text+0x311): undefined reference to `BIO_new'
jwt.cpp:(.text+0x31c): undefined reference to `BIO_push'
jwt.cpp:(.text+0x331): undefined reference to `BIO_set_flags'
jwt.cpp:(.text+0x35f): undefined reference to `BIO_write'
jwt.cpp:(.text+0x386): undefined reference to `BIO_ctrl'
jwt.cpp:(.text+0x3b5): undefined reference to `BIO_ctrl'
jwt.cpp:(.text+0x3ec): undefined reference to `BIO_free_all'
//usr/local/lib/libjwtxx.a(jwt.cpp.o): In function `JWTXX::Base64URL::decode(std::string)':
jwt.cpp:(.text+0x54c): undefined reference to `BIO_new_mem_buf'
jwt.cpp:(.text+0x554): undefined reference to `BIO_f_base64'
jwt.cpp:(.text+0x55c): undefined reference to `BIO_new'
jwt.cpp:(.text+0x567): undefined reference to `BIO_push'
jwt.cpp:(.text+0x57c): undefined reference to `BIO_set_flags'
jwt.cpp:(.text+0x5c8): undefined reference to `BIO_read'
jwt.cpp:(.text+0x5d7): undefined reference to `BIO_free_all'
//usr/local/lib/libjwtxx.a(jwt.cpp.o): In function `(anonymous namespace)::createKey(JWTXX::Algorithm, std::string const&, std::function<std::string ()> const&)':
jwt.cpp:(.text+0x6f8): undefined reference to `EVP_sha256'
jwt.cpp:(.text+0x727): undefined reference to `EVP_sha384'
jwt.cpp:(.text+0x756): undefined reference to `EVP_sha512'
jwt.cpp:(.text+0x785): undefined reference to `EVP_sha256'
jwt.cpp:(.text+0x7bb): undefined reference to `EVP_sha384'
jwt.cpp:(.text+0x7f1): undefined reference to `EVP_sha512'
jwt.cpp:(.text+0x827): undefined reference to `EVP_sha256'
jwt.cpp:(.text+0x85d): undefined reference to `EVP_sha384'
jwt.cpp:(.text+0x893): undefined reference to `EVP_sha512'
//usr/local/lib/libjwtxx.a(jwt.cpp.o): In function `JWTXX::enableOpenSSLErrors()::OpenSSLErrors::OpenSSLErrors()':
jwt.cpp:(.text+0x126d): undefined reference to `OPENSSL_init_crypto'
jwt.cpp:(.text+0x127c): undefined reference to `OPENSSL_init_crypto'
//usr/local/lib/libjwtxx.a(jwt.cpp.o): In function `JWTXX::Utils::EVPKeyDeleter::operator()(evp_pkey_st*)':
jwt.cpp:(.text._ZN5JWTXX5Utils13EVPKeyDeleterclEP11evp_pkey_st[_ZN5JWTXX5Utils13EVPKeyDeleterclEP11evp_pkey_st]+0x18): undefined reference to `EVP_PKEY_free'
//usr/local/lib/libjwtxx.a(jwt.cpp.o): In function `JWTXX::Utils::EVPMDCTXDeleter::operator()(evp_md_ctx_st*)':
jwt.cpp:(.text._ZN5JWTXX5Utils15EVPMDCTXDeleterclEP13evp_md_ctx_st[_ZN5JWTXX5Utils15EVPMDCTXDeleterclEP13evp_md_ctx_st]+0x18): undefined reference to `EVP_MD_CTX_free'
//usr/local/lib/libjwtxx.a(jwt.cpp.o): In function `JWTXX::Base64URL::Block::Block(unsigned long)':
jwt.cpp:(.text._ZN5JWTXX9Base64URL5BlockC2Em[_ZN5JWTXX9Base64URL5BlockC5Em]+0x22): undefined reference to `CRYPTO_malloc'
//usr/local/lib/libjwtxx.a(jwt.cpp.o): In function `JWTXX::Base64URL::Block::~Block()':
jwt.cpp:(.text._ZN5JWTXX9Base64URL5BlockD2Ev[_ZN5JWTXX9Base64URL5BlockD5Ev]+0x21): undefined reference to `CRYPTO_free'
//usr/local/lib/libjwtxx.a(jwt.cpp.o): In function `JWTXX::Keys::HMAC::sign(void const*, unsigned long) const':
jwt.cpp:(.text._ZNK5JWTXX4Keys4HMAC4signEPKvm[_ZNK5JWTXX4Keys4HMAC4signEPKvm]+0x2b): undefined reference to `EVP_MD_CTX_new'
jwt.cpp:(.text._ZNK5JWTXX4Keys4HMAC4signEPKvm[_ZNK5JWTXX4Keys4HMAC4signEPKvm]+0xf9): undefined reference to `EVP_DigestInit_ex'
jwt.cpp:(.text._ZNK5JWTXX4Keys4HMAC4signEPKvm[_ZNK5JWTXX4Keys4HMAC4signEPKvm]+0x1b8): undefined reference to `EVP_PKEY_new_mac_key'
jwt.cpp:(.text._ZNK5JWTXX4Keys4HMAC4signEPKvm[_ZNK5JWTXX4Keys4HMAC4signEPKvm]+0x2a0): undefined reference to `EVP_DigestSignInit'
jwt.cpp:(.text._ZNK5JWTXX4Keys4HMAC4signEPKvm[_ZNK5JWTXX4Keys4HMAC4signEPKvm]+0x34b): undefined reference to `EVP_DigestUpdate'
jwt.cpp:(.text._ZNK5JWTXX4Keys4HMAC4signEPKvm[_ZNK5JWTXX4Keys4HMAC4signEPKvm]+0x3e4): undefined reference to `EVP_DigestSignFinal'
jwt.cpp:(.text._ZNK5JWTXX4Keys4HMAC4signEPKvm[_ZNK5JWTXX4Keys4HMAC4signEPKvm]+0x4b2): undefined reference to `EVP_DigestSignFinal'
//usr/local/lib/libjwtxx.a(jwt.cpp.o): In function `JWTXX::Keys::PEM::sign(void const*, unsigned long) const':
jwt.cpp:(.text._ZNK5JWTXX4Keys3PEM4signEPKvm[_ZNK5JWTXX4Keys3PEM4signEPKvm]+0xd9): undefined reference to `EVP_DigestSignInit'
jwt.cpp:(.text._ZNK5JWTXX4Keys3PEM4signEPKvm[_ZNK5JWTXX4Keys3PEM4signEPKvm]+0x184): undefined reference to `EVP_DigestUpdate'
jwt.cpp:(.text._ZNK5JWTXX4Keys3PEM4signEPKvm[_ZNK5JWTXX4Keys3PEM4signEPKvm]+0x22f): undefined reference to `EVP_DigestSignFinal'
jwt.cpp:(.text._ZNK5JWTXX4Keys3PEM4signEPKvm[_ZNK5JWTXX4Keys3PEM4signEPKvm]+0x306): undefined reference to `EVP_DigestSignFinal'
//usr/local/lib/libjwtxx.a(jwt.cpp.o): In function `JWTXX::Keys::PEM::verify(void const*, unsigned long, std::string const&) const':
jwt.cpp:(.text._ZNK5JWTXX4Keys3PEM6verifyEPKvmRKSs[_ZNK5JWTXX4Keys3PEM6verifyEPKvmRKSs]+0x9a): undefined reference to `EVP_DigestVerifyInit'
jwt.cpp:(.text._ZNK5JWTXX4Keys3PEM6verifyEPKvmRKSs[_ZNK5JWTXX4Keys3PEM6verifyEPKvmRKSs]+0x133): undefined reference to `EVP_DigestUpdate'
jwt.cpp:(.text._ZNK5JWTXX4Keys3PEM6verifyEPKvmRKSs[_ZNK5JWTXX4Keys3PEM6verifyEPKvmRKSs]+0x214): undefined reference to `EVP_DigestVerifyFinal'
//usr/local/lib/libjwtxx.a(jwt.cpp.o): In function `JWTXX::Keys::PEM::initCTX() const':
jwt.cpp:(.text._ZNK5JWTXX4Keys3PEM7initCTXEv[_ZNK5JWTXX4Keys3PEM7initCTXEv]+0x14): undefined reference to `EVP_MD_CTX_new'
jwt.cpp:(.text._ZNK5JWTXX4Keys3PEM7initCTXEv[_ZNK5JWTXX4Keys3PEM7initCTXEv]+0xc4): undefined reference to `EVP_DigestInit_ex'
//usr/local/lib/libjwtxx.a(utils.cpp.o): In function `(anonymous namespace)::X509Deleter::operator()(x509_st*)':
utils.cpp:(.text+0xce): undefined reference to `X509_free'
//usr/local/lib/libjwtxx.a(utils.cpp.o): In function `(anonymous namespace)::readPublicKey(std::string const&)':
utils.cpp:(.text+0x266): undefined reference to `PEM_read_PUBKEY'
//usr/local/lib/libjwtxx.a(utils.cpp.o): In function `(anonymous namespace)::readCert(std::string const&)':
utils.cpp:(.text+0x427): undefined reference to `PEM_read_X509'
utils.cpp:(.text+0x46e): undefined reference to `X509_get_pubkey'
//usr/local/lib/libjwtxx.a(utils.cpp.o): In function `JWTXX::Utils::readPEMPrivateKey(std::string const&, std::function<std::string ()>)':
utils.cpp:(.text+0x7a5): undefined reference to `PEM_read_PrivateKey'
//usr/local/lib/libjwtxx.a(utils.cpp.o): In function `JWTXX::Utils::OPENSSLError()':
utils.cpp:(.text+0xdbf): undefined reference to `ERR_get_error'
utils.cpp:(.text+0xdd6): undefined reference to `ERR_error_string_n'
//usr/local/lib/libjwtxx.a(json.cpp.o): In function `json_decref':
json.cpp:(.text+0x5a): undefined reference to `json_delete'
//usr/local/lib/libjwtxx.a(json.cpp.o): In function `(anonymous namespace)::toString(json_t const*)':
json.cpp:(.text+0x154): undefined reference to `json_string_value'
json.cpp:(.text+0x187): undefined reference to `json_integer_value'
json.cpp:(.text+0x1aa): undefined reference to `json_real_value'
json.cpp:(.text+0x1ea): undefined reference to `json_dumps'
//usr/local/lib/libjwtxx.a(json.cpp.o): In function `JWTXX::toJSON(std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&)':
json.cpp:(.text+0x2b6): undefined reference to `json_object'
json.cpp:(.text+0x31a): undefined reference to `json_string'
json.cpp:(.text+0x346): undefined reference to `json_object_set_new'
json.cpp:(.text+0x382): undefined reference to `json_dumps'
//usr/local/lib/libjwtxx.a(json.cpp.o): In function `JWTXX::fromJSON(std::string const&)':
json.cpp:(.text+0x456): undefined reference to `json_loads'
json.cpp:(.text+0x6eb): undefined reference to `json_object_iter'
json.cpp:(.text+0x6f3): undefined reference to `json_object_iter_key'
json.cpp:(.text+0x7ae): undefined reference to `json_object_key_to_iter'
json.cpp:(.text+0x7cb): undefined reference to `json_object_iter_next'
json.cpp:(.text+0x7d3): undefined reference to `json_object_iter_key'
json.cpp:(.text+0x7f3): undefined reference to `json_object_key_to_iter'
json.cpp:(.text+0x7fb): undefined reference to `json_object_iter_value'
collect2: error: ld returned 1 exit status

**Comment by madf** [comment]
-lssl is unnecessary. Where do you put -lcrypto? It should go after the -ljwtxx.

**Comment by madf** [comment]
You also need -ljansson after the -ljwtxx.

**Comment by MadMax411** [comment]
At the first time I try in front of -ljwtxx, now behind.

$ g++ -std=c++11 test_jwt.cpp -ljwtxx -lcrypto

//usr/local/lib/libjwtxx.a(jwt.cpp.o): In function `JWTXX::enableOpenSSLErrors()::OpenSSLErrors::OpenSSLErrors()':
jwt.cpp:(.text+0x126d): undefined reference to `OPENSSL_init_crypto'
jwt.cpp:(.text+0x127c): undefined reference to `OPENSSL_init_crypto'
//usr/local/lib/libjwtxx.a(jwt.cpp.o): In function `JWTXX::Utils::EVPMDCTXDeleter::operator()(evp_md_ctx_st*)':
jwt.cpp:(.text._ZN5JWTXX5Utils15EVPMDCTXDeleterclEP13evp_md_ctx_st[_ZN5JWTXX5Utils15EVPMDCTXDeleterclEP13evp_md_ctx_st]+0x18): undefined reference to `EVP_MD_CTX_free'
//usr/local/lib/libjwtxx.a(jwt.cpp.o): In function `JWTXX::Keys::HMAC::sign(void const*, unsigned long) const':
jwt.cpp:(.text._ZNK5JWTXX4Keys4HMAC4signEPKvm[_ZNK5JWTXX4Keys4HMAC4signEPKvm]+0x2b): undefined reference to `EVP_MD_CTX_new'
//usr/local/lib/libjwtxx.a(jwt.cpp.o): In function `JWTXX::Keys::PEM::initCTX() const':
jwt.cpp:(.text._ZNK5JWTXX4Keys3PEM7initCTXEv[_ZNK5JWTXX4Keys3PEM7initCTXEv]+0x14): undefined reference to `EVP_MD_CTX_new'
//usr/local/lib/libjwtxx.a(json.cpp.o): In function `json_decref':
json.cpp:(.text+0x5a): undefined reference to `json_delete'
//usr/local/lib/libjwtxx.a(json.cpp.o): In function `(anonymous namespace)::toString(json_t const*)':
json.cpp:(.text+0x154): undefined reference to `json_string_value'
json.cpp:(.text+0x187): undefined reference to `json_integer_value'
json.cpp:(.text+0x1aa): undefined reference to `json_real_value'
json.cpp:(.text+0x1ea): undefined reference to `json_dumps'
//usr/local/lib/libjwtxx.a(json.cpp.o): In function `JWTXX::toJSON(std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&)':
json.cpp:(.text+0x2b6): undefined reference to `json_object'
json.cpp:(.text+0x31a): undefined reference to `json_string'
json.cpp:(.text+0x346): undefined reference to `json_object_set_new'
json.cpp:(.text+0x382): undefined reference to `json_dumps'
//usr/local/lib/libjwtxx.a(json.cpp.o): In function `JWTXX::fromJSON(std::string const&)':
json.cpp:(.text+0x456): undefined reference to `json_loads'
json.cpp:(.text+0x6eb): undefined reference to `json_object_iter'
json.cpp:(.text+0x6f3): undefined reference to `json_object_iter_key'
json.cpp:(.text+0x7ae): undefined reference to `json_object_key_to_iter'
json.cpp:(.text+0x7cb): undefined reference to `json_object_iter_next'
json.cpp:(.text+0x7d3): undefined reference to `json_object_iter_key'
json.cpp:(.text+0x7f3): undefined reference to `json_object_key_to_iter'
json.cpp:(.text+0x7fb): undefined reference to `json_object_iter_value'
collect2: error: ld returned 1 exit status

**Comment by MadMax411** [comment]
Nearly...

$ g++ -std=c++11 test_jwt.cpp -ljwtxx -lcrypto -ljansson


//usr/local/lib/libjwtxx.a(jwt.cpp.o): In function `JWTXX::enableOpenSSLErrors()::OpenSSLErrors::OpenSSLErrors()':
jwt.cpp:(.text+0x126d): undefined reference to `OPENSSL_init_crypto'
jwt.cpp:(.text+0x127c): undefined reference to `OPENSSL_init_crypto'
//usr/local/lib/libjwtxx.a(jwt.cpp.o): In function `JWTXX::Utils::EVPMDCTXDeleter::operator()(evp_md_ctx_st*)':
jwt.cpp:(.text._ZN5JWTXX5Utils15EVPMDCTXDeleterclEP13evp_md_ctx_st[_ZN5JWTXX5Utils15EVPMDCTXDeleterclEP13evp_md_ctx_st]+0x18): undefined reference to `EVP_MD_CTX_free'
//usr/local/lib/libjwtxx.a(jwt.cpp.o): In function `JWTXX::Keys::HMAC::sign(void const*, unsigned long) const':
jwt.cpp:(.text._ZNK5JWTXX4Keys4HMAC4signEPKvm[_ZNK5JWTXX4Keys4HMAC4signEPKvm]+0x2b): undefined reference to `EVP_MD_CTX_new'
//usr/local/lib/libjwtxx.a(jwt.cpp.o): In function `JWTXX::Keys::PEM::initCTX() const':
jwt.cpp:(.text._ZNK5JWTXX4Keys3PEM7initCTXEv[_ZNK5JWTXX4Keys3PEM7initCTXEv]+0x14): undefined reference to `EVP_MD_CTX_new'
collect2: error: ld returned 1 exit status

**Comment by madf** [comment]
What version of openssl do you use?

**Comment by MadMax411** [comment]
I updated my linux mint to version 1.1.0d. I thought at the beginning that my default version was to old.

$ openssl version
OpenSSL 1.1.0d  26 Jan 2017

**Comment by madf** [comment]
I think jwtxx should work fine with 0.9.8 but I haven't tried.

**Comment by MadMax411** [comment]
Ouch, I used that version before and I didn't know about the other libraries. I'm going to try a downgrade of OpenSSL.

**Comment by madf** [comment]
No, 1.1.0 is also fine.

**Comment by MadMax411** [comment]
Okay, I stay on 1.1.0d.

**Comment by madf** [comment]
Please give me a complete code of your example and command you use to build it. I'll try it for myself.

**Comment by madf** [comment]
Also, what is the version of gcc?

**Comment by MadMax411** [comment]
I try only to compile it without any key file, because I have only a public key to decrypt a jwt. Or do you have an example for public key decryption? I want to do the same like this debugger: https://jwt.io/

gcc version:
$ g++ --version
g++ (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

Compile command:
$ g++ -std=c++11 test_jwt.cpp -ljwtxx -lcrypto -ljansson

Source code:

#include < iostream >
# Remove the spaces, because with spaces the comments delete the include

#include <jwtxx/jwt.h>

using namespace JWTXX;

int main()
{
    // Create
    JWT jwt(Algorithm::RS256, {{"sub", "user"}, {"iss", "madf"}});
    auto token = jwt.token("");

    // Parse
    try
    {
        JWT jwt2(token, Key(Algorithm::RS256, "") );
        std::cout << "Algorithm: " << algToString(jwt2.alg()) << "\n"
                  << "Subject:   " << jwt2.claim("sub") << "\n"
                  << "Issuer:    " << jwt2.claim("iss") << std::endl;
    }
    catch (const JWT::Error& error)
    {
        std::cerr << "Error parsing token: " << error.what() << std::endl;
    }

    return 0;
}

**Comment by madf** [comment]
Ok, I tried your code on Mac, it compiles and links fine. But here I have an older OpenSSL:
`openssl version
OpenSSL 1.0.2j  26 Sep 2016`
I also checked Travis CI, it shows:
`-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found suitable version "1.0.1f", minimum required is "0.9.8") `
So probably the code is incompatible with OpenSSL 1.1.x. I will try when I get to a Linux machine. Currently you can try with older OpenSSL - 1.0.x or 0.9.8.

**Comment by MadMax411** [comment]
Thanks in advance! I'm going to use 1.0.2j from OpenSSL: https://www.openssl.org/source/old/1.0.2/

**Comment by madf** [comment]
I've probably figured out your problem. I tried to build your example with openssl-1.1.something and everything went fine. Mint is a binary distribution. It means that it usually provides libraries and headers separately. The headers come in libssl-dev package and its version should fit the openssl package version. So if you use openssl-1.1.* the libssl-dev should also be 1.1.*. In your case it seems you used a newer openssl with older headers. Please check.

**Comment by madf** [comment]
If you use custom openssl build from the official sources you need to provide a path to the 'include' folder. `g++ -I/home/<user>/openssl-1.1.<something>/include ...`

**Comment by MadMax411** [comment]
You're right! I have to include the correct library version of openssl. The manually installed version 1.0.2j is located in "/usr/local/ssl/".

` $ g++ -std=c++11 -o testjwt -I/usr/local/ssl/include test_jwt.cpp -ljwtxx -lcrypto -ljansson`

Now it compiles perfectly! Thank you for your support and help!

**Comment by madf** [comment]
No problem. I'm closing the issue then.
